[repository]
name = "hyprland-fix-hdr-screenshare"
authors = ["daniel"]
commit_pins = [
    # Hyprland                                  hyprland-fix-hdr-screenshare
    ["af923e30d1d24f1f4a4f5cb8308065173c1d9539", "db870de405f9deee8b778271745ca4674c852ae1"], # v0.55.0
    ["36b2e0cfe0c6094dbc47bd42a437431315bb3087", "0e2fcf30d6ea7749f786651e83468134f6e564b9"], # v0.56.0
]

[fix-hdr-screenshare]
description = "Disable the HDR unmodified-copy MRT path used for screenshare"
authors = ["daniel"]
output = "fix-hdr-screenshare.so"
build = [
    "make",
]
